apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels: 
        app: auth
    spec:
      containers:
        - name: auth
          image: zoeharris168/auth
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
          resources:                  # ✅ Minimal resources for testing
            requests:
              cpu: "50m"             # tiny guaranteed CPU
              memory: "64Mi"         # tiny guaranteed memory
            limits:
              cpu: "100m"            # max CPU allowed
              memory: "128Mi"        # max memory allowed

---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP